# Generated by Django 3.0.5 on 2020-04-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('rating', models.TextField(default='NaN', max_length=65536)),
                ('feedback', models.TextField(default='NaN', max_length=65536)),
            ],
        ),
    ]
